
- name: Adicionando o usuaio devops
  user:
    name: "{{item.name}}"
    state: present
    shell: '/bin/bash'
    home: "{{item.home}}"
    password: '$1$I7wRILCi$L9C1pPbD.VDerKFmg7oUj1'
  with_items:
    - {name: devops, home: /srv/devops}
    - {name: developer, home: /srv/developer}
    - {name: felipe, home: /srv/felipe}
